### ISSUE TITLE
Apacite style does not work

### ISSUE THREAD

**Issue by chris-konrad** [moorepants/bmd-templates#15]
When attempting to use create a bibliography from .bib with bibtex/biblatex, the suggested style apacite makes the compilation fail. Bibstyles plain and apa seem to work, only apacite causes problems. Is there a reason why we specifically recommend apacite? I tried adding \RequirePackage{apacite} to the class file but that did not help. 

See the example .bib-file attached.

**Comment by moorepants** [comment]
I thought I tested this for a bib file, but can't quite recall.

I think that I used this answer to justify the recommendation: https://tex.stackexchange.com/a/35813/17788 and I thought I tested it.

The APA citation and bibliography style should work using a bib file or references listed in the tex document. If it doesn't we need to fix it.

Do you want to investigate a fix? Or shall I?

**Comment by moorepants** [comment]
I just tried this and added `\usepackage{apacite}` to the preamble. It had errors in building and the format was all screwed up. The last release of apacite was 2013: https://ctan.org/tex-archive/biblio/bibtex/contrib/apacite/ I wonder if it even works anymore.

**Comment by moorepants** [comment]
Looking at this https://tex.stackexchange.com/questions/263793/what-is-the-relationship-between-natbib-apacite-package-and-apa-document-class

I tried just changing the bib style to `apalike` and that seems to work. So natbib + the `apalike` style might be the fix.
