### ISSUE TITLE
Large header is repeated on all odd pages, should only be on the first page.

### ISSUE THREAD

**Issue by moorepants** [moorepants/bmd-templates#2]
Right now I have it in the odd pages. Works for the abstract because it is only two pages, but needs to be fixed for the paper.

**Comment by chris-konrad** [comment]
What about moving the images from the header to the title. That way they will only appear on the first page. Could be tricky for spacing though.

**Comment by moorepants** [comment]
Yes, that could be solution. Right now the template is a bit of hack. The "title" isn't a real latex title. I think making use of the fancyhdr package is the easiest approach to fix several issues regarding how the headers, footers, and page numbers work. Otherwise, learning how to properly override the headers, footers, page numbers (and title) in the .cls file is needed.
