### ISSUE TITLE
Proofreading abstract review sheet

### ISSUE THREAD

**Issue by chris-konrad** [moorepants/bmd-templates#20]
Hi, I looked at the abstract review sheets! Looks good so far, the instructions are clear. Conversion to docx looks sound to me. Some issues and ideas below:

- Instructions, bullet point six: Missing comma after "sheet"
- Instructions, second level bullet points: Maybe add end of sentence punctuation to be consistent with the first level bullet points?
- Point scale: Maybe add end of sentence punctuation to each line?

**Other ideas:** 

- The field "Your score" is easy to miss . Maybe put a box around it so that it sticks out more? Additionally, horizontal lines above each section could help the eye to identify where the document needs to be filled and where not (See screenshot with example).
- Maybe add a note, that shortcomings in template use should not be included in the assessment?

**Example of section breaks with horizontal lines:**
![image](https://user-images.githubusercontent.com/115986935/223456813-9a258d3d-42c4-43fb-80f1-bd2c6c72fda1.png)

**Comment by moorepants** [comment]
Hi @chrismo-schmidt this is great. If you have already made these changes, can you just make a PR? All sounds good.

**Comment by moorepants** [comment]
All things addressed. Thanks.
