### ISSUE TITLE
It is not clear what should and shouldn't be included on the headers and footers after the first page

### ISSUE THREAD

**Issue by moorepants** [moorepants/bmd-templates#3]
Should the copyright and issn be on every page?

Should doi be on every page?

**Comment by chris-konrad** [comment]
[Here](https://dapp.orvium.io/deposits/624729750bd70f0d57ec64f6/view) we can have a look at other work published in The Evolving Scholar. Templates differ a bit, but none I checked have issn/doi/copyright on every page.

**Comment by moorepants** [comment]
I don't think they've settled on a template, as it seemed the ones given to me where new versions.

We can make pages 2 and on only have "Evolving Scholar (2023) .... http/dx.doi.org" in the header and have "2 of 10" in the bottom right footer. That means the copyright, issn, logos, conference name/info are only on first page.

**Comment by chris-konrad** [comment]
Yes. And i guess this means we should use fancyhdr (refering also to #2)
