### ISSUE TITLE
The equation may not be converting to docx from the odt export

### ISSUE THREAD

**Issue by moorepants** [moorepants/bmd-templates#5]

**Comment by chris-konrad** [comment]
I tried the export, the equation works for me.

**Comment by chris-konrad** [comment]
Thats how it looks for me:
![image](https://user-images.githubusercontent.com/115986935/211791357-6a87f66e-2198-48a1-8674-edd58247f882.png)

**Comment by moorepants** [comment]
Ok, equation comes through. Great. I didn't see in the gmail preview.
