### ISSUE TITLE
Errors in original odt template

### ISSUE THREAD

**Issue by chris-konrad** [moorepants/bmd-templates#6]
Here is a list of small errors in the .odt template:

Line 1: Typo "web site" instead of "website"
Lines 7, 8, 9: Inconsistent use of whitespace between number and "pt". Change to "18 pt", "10 pt" and "8 pt"
Line 10: It says that the abstract heading should be "11 pt", but it actually is 9 pt in the example. Change the font size of the heading. 

Figure 1: The text says images should be at least 300 dpi, but the example image is only 120 dpi. Do we have a high-res version?

Lastly, is it correct that there is no footer on the last page?

**Comment by moorepants** [comment]
Thanks, I'll work on these.

I'm not sure what to do about the footer. It wasn't clear to me what exactly was desired from the sample templates I was given. I'll ask the library people. Also see #3

**Comment by moorepants** [comment]
Fixed with https://github.com/moorepants/bmd-templates/commit/bc3b1ccac484e062146f870ed2414620504e275d
