### ISSUE TITLE
TU Delft Open logo moves to a different place after export from .odt to .docx

### ISSUE THREAD

**Issue by chris-konrad** [moorepants/bmd-templates#8]
![image](https://user-images.githubusercontent.com/115986935/211791150-6f3c4da3-c50a-46f6-b220-0804bf251ffd.png)

Should be an easy fix. Anchor the TU Delft Open logo to the paragraph within the table in the header instead anchoring it to "page"
(Rightclick -> anchor -> To Paragraph, then move into the table)

**Comment by moorepants** [comment]
My current process is editing in libreoffice, then exporting. Is there a way to fix it in libreoffice so the export works?

**Comment by chris-konrad** [comment]
Yes, the way I described is meant to be executed in Libreoffice. Then the export to office should keep the logo in the right location.

**Comment by moorepants** [comment]
Ok, I'll try it.

**Comment by NicolNastase** [comment]
![Screen Shot 2023-01-11 at 13 20 01](https://user-images.githubusercontent.com/112410386/211811588-332ccfe2-aa73-4d77-b916-a6fc91c61c49.png)
Hi, this is how the last docx version from Antonio looks like - I supposed it's anchored in the header but still with a minor underline.

**Comment by moorepants** [comment]
I used Christophs recommendation and anchored the images "to paragraph" in libreoffice. The export now seems to work.

Fixed in:

https://github.com/moorepants/bmd-templates/commit/c8ba8f21e6e8297a0c3467176c81185f1d8fdc62

**Comment by moorepants** [comment]
Here is the current docx export:
[bmd2023a.docx](https://github.com/moorepants/bmd-templates/files/10392661/bmd2023a.docx)

**Comment by moorepants** [comment]
@NicolNastase Can you check?

**Comment by NicolNastase** [comment]
Checked! It's in order, good to use!
